#!/usr/bin/env bash

js_lines="$(find . -iname '*.js' | grep -v node_modules | grep -v pixi | xargs cat | wc -l)"
pl_lines="$(find . -iname '*.pl' | grep -v node_modules | xargs cat | wc -l)"
html_lines="$(find . -iname '*.html' | grep -v node_modules | xargs cat | wc -l)"

find . -iname '*.js' | grep -v node_modules | grep -v pixi
find . -iname '*.pl' | grep -v node_modules
find . -iname '*.html' | grep -v node_modules

expr $js_lines + $html_lines + $pl_lines
