#!/usr/bin/env bash

ENV_JS='/usr/src/app/public/env.js'

set_env() {
    if [[ ! -z "$2" ]]; then
        echo "window.$1 = $3;" >> "$ENV_JS"
    else
        echo "window.$1 = $4;" >> "$ENV_JS"
    fi
}

echo '' > "$ENV_JS"
set_env IO_URL "$IO_URL" "'$IO_URL'" null
set_env USE_SMOOTHING "$USE_SMOOTHING" true false

node .
