var constants = require('./public/shared/gj_constants');
var tile_types = constants.tile_types;

module.exports = {
    1: tile_types.SOLID,
    2: tile_types.SOLID,
    3: tile_types.SOLID,
    4: tile_types.NO_COLLISION,
    5: tile_types.NO_COLLISION,
    6: tile_types.NO_COLLISION,
    7: tile_types.ONE_WAY,
    8: tile_types.NO_COLLISION,
    9: tile_types.SOLID,
    10: tile_types.SOLID,
    11: tile_types.SOLID,
    12: tile_types.NO_COLLISION,
    13: tile_types.NO_COLLISION,
    14: tile_types.NO_COLLISION,
    15: tile_types.ONE_WAY,
    16: tile_types.ONE_WAY,

    17: tile_types.SOLID,
    18: tile_types.SOLID,
    19: tile_types.SOLID,
    20: tile_types.NO_COLLISION,
    21: tile_types.NO_COLLISION,
    22: tile_types.ONE_WAY,
    23: tile_types.ONE_WAY,
    24: tile_types.ONE_WAY,
    25: tile_types.SOLID,
    26: tile_types.SOLID,
    27: tile_types.SOLID,
    28: tile_types.NO_COLLISION,
    29: tile_types.NO_COLLISION,
    30: tile_types.NO_COLLISION,
    31: tile_types.NO_COLLISION,
    32: tile_types.ONE_WAY,

    33: tile_types.NO_COLLISION,
    34: tile_types.NO_COLLISION,
    35: tile_types.NO_COLLISION,
    36: tile_types.NO_COLLISION,
    37: tile_types.NO_COLLISION,
    38: tile_types.ONE_WAY,
    39: tile_types.NO_COLLISION,
    40: tile_types.NO_COLLISION,
    41: tile_types.NO_COLLISION,
    42: tile_types.NO_COLLISION,
    43: tile_types.NO_COLLISION,
    44: tile_types.NO_COLLISION,
    45: tile_types.NO_COLLISION,
    46: tile_types.ONE_WAY,
    47: tile_types.SOLID,
    48: tile_types.SOLID,

    49: tile_types.NO_COLLISION,
    50: tile_types.FATAL,
    51: tile_types.FATAL,
    57: tile_types.NO_COLLISION,
    58: tile_types.FATAL,
    59: tile_types.FATAL,

    65: tile_types.SOLID,
    66: tile_types.SOLID,
    67: tile_types.SOLID,
    68: tile_types.ONE_WAY,
    69: tile_types.ONE_WAY,
    70: tile_types.NO_COLLISION,
    71: tile_types.NO_COLLISION,
    72: tile_types.NO_COLLISION,
    73: tile_types.SOLID,

    81: tile_types.SOLID,
    82: tile_types.SOLID,
    83: tile_types.SOLID,
    84: tile_types.NO_COLLISION,
    85: tile_types.NO_COLLISION,
    86: tile_types.NO_COLLISION,
    87: tile_types.NO_COLLISION,
    88: tile_types.NO_COLLISION,

    97: tile_types.NO_COLLISION,
    98: tile_types.NO_COLLISION,
    99: tile_types.NO_COLLISION,
    100: tile_types.NO_COLLISION,
    101: tile_types.NO_COLLISION,
    102: tile_types.ONE_WAY,
    103: tile_types.SOLID,
    104: tile_types.SOLID,

    113: tile_types.SOLID,
    114: tile_types.FATAL,
    115: tile_types.FATAL
};

